enabled: true
also_exclude:
  - "alembic/**/*"

request_review: author
labels:
  - "Type: Style"
  - "Priority: 3"

restylers:
  - jq:
      enabled: false
  - reorder-python-imports:
      enabled: false
  - isort:
      enabled: true
  - jdt:
      enabled: true
  - "*"
  - yapf:
      arguments: ["--style pyproject.toml"]
