version = 1

exclude_patterns = ["alembic/**"]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 80

[[transformers]]
name = "isort"

[[transformers]]
name = "black"
