[tool.poetry]
name = "tickets-plus"
version = "0.1.1"
description = "A companion bot adding some extensions to Tickets discord bot. Experimental."
authors = ["Tech. TTGames <50541739+Tech-TTGames@users.noreply.github.com>"]
license = "EPL-2.0"
readme = "README.md"
packages = [{include = "tickets_plus"}]
exclude = ["branding"]

[tool.poetry.dependencies]
python = "^3.11"
"discord.py" = "^2.3.2"
SQLAlchemy = {extras = ["asyncio"], version = "^2.0.25"}
alembic = {extras = ["tz"], version = "^1.13.1"}
asyncpg = { version = "^0.29.0", optional = true }
aiosqlite = { version = "^0.19.0", optional = true }
pynacl = "^1.5.0"
tornado = "^6.4"
tzdata = "^2023.4"

[tool.poetry.extras]
sqlite = ["aiosqlite"]
pgsql = ["asyncpg"]
database = ["asyncpg", "aiosqlite"]

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
yapf = "^0.40.2"
pylint = "^3.0.3"
pdoc = "^14.3.0"

[tool.poetry.scripts]
start = "tickets_plus.__main__:main"
migrate = "toolbox.migrate:main"
nuke = "toolbox.nuke:main"

[tool.yapf]
based_on_style = "google"
column_limit = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
