[tool.poetry]
name = "tickets-plus"
version = "0.1.0"
description = "A companion bot adding some extensions to Tickets discord bot. Experimental."
authors = ["Tech. TTGames <50541739+Tech-TTGames@users.noreply.github.com>"]
license = "EPL-2.0"
readme = "README.md"
packages = [{include = "tickets_plus"}]
exclude = ["branding"]

[tool.poetry.dependencies]
python = "^3.11"
"discord.py" = "^2.2.2"
SQLAlchemy = {extras = ["asyncio"], version = "^2.0.6"}
alembic = {extras = ["tz"], version = "^1.10.2"}
asyncpg = { version = "^0.27.0", optional = true }
aiosqlite = { version = "^0.18.0", optional = true }

[tool.poetry.extras]
sqlite = ["aiosqlite"]
pgsql = ["asyncpg"]
database = ["asyncpg", "aiosqlite"]

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
yapf = "^0.32.0"
pylint = "^2.17.0"
toml = "^0.10.2"
pdoc = "^13.0.0"

[tool.poetry.scripts]
start = "tickets_plus.__main__:main"
migrate = "toolbox.migrate:main"
nuke = "toolbox.nuke:main"

[tool.yapf]
based_on_style = "google"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
